spring:
    datasource:
       url: jdbc:mysql://192.168.9.105:3307/edu_cloud_platform?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&useSSL=false
       username: root
       password: 12345678
       driver-class-name: com.mysql.jdbc.Driver
       maxActive: 20
       initialSize: 1     
       maxWait: 60000
       minIdle: 1
       timeBetweenEvictionRunsMillis: 60000
       minEvictableIdleTimeMillis: 300000
       validationQuery: select 'x'
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
       maxOpenPreparedStatements: 20
        #如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false
       poolPreparedStatements: false
    redis:
        database: 0
        host: 192.168.9.100
        port: 6379
        password: 
        timeout: 1000
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
          max-wait: 100
sys:
  redis: 
    token: 1800
resource:
   uploadurl: /home/workspace/upload
   address: anyfile/
   prefix: http://192.168.9.105/anyupload/






